# fly.toml file generated for grafana-agent-dev on 2022-04-06T13:07:15-07:00

app = "spydefiprom"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[http_service]
 internal_port = 12345
 force_https = true
 auto_stop_machines = false
 auto_start_machines = true
 min_machines_running = 0
 processes = ["app"]

[[services]]
 auto_stop_machines = false
